### ISSUE TITLE
the ORM QuerySubscriber reuse the Doctrine code instead of reimplementing

### ISSUE THREAD

**Issue by stof** [KnpLabs/knp-components#114]
It should rely on the Paginator class available in Doctrine 2.2+ (2.0 and 2.1 are EOLed since several years now) instead of copying most of the logic.

Exposing the few config flag available in the class (there is 2 boolean flags) would allow users to choose the best strategy according to their needs. There is no best strategy fitting all use cases, as seen in https://github.com/KnpLabs/knp-components/pull/77#issuecomment-53540910

**Comment by ostrolucky** [comment]
This can be closed since it was implemented in https://github.com/KnpLabs/knp-components/pull/115
