### ISSUE TITLE
DBALQueryBuilderSubscriber should be removed as it doesn't serve any purpose. 

### ISSUE THREAD

**Issue by gondo** [KnpLabs/knp-components#120]
class `PaginationSubscriber` [1] defines subscribers to execute pagination 
however the order of subscriber is broken, as code in `DBALQueryBuilderSubscriber` will never be executed, because it expect `target` to be instanceof `QueryBuilder`.
this will never happen because `QueryBuilderSubscriber` is executed sooner and it transform `QueryBuilder` into `Query`

`DBALQueryBuilderSubscriber` should be removed as it doesn't serve any purpose and there are no tests referring or testing this subscriber.

[1]
https://github.com/KnpLabs/knp-components/blob/756c44523db9cf125381cba2cb08160fd184fb24/src/Knp/Component/Pager/Event/Subscriber/Paginate/PaginationSubscriber.php

**Comment by polc** [comment]
Thanks for reporting this issue, I believe this subscriber was keep for BC. Worth removing it in a next major release then.
