### ISSUE TITLE
Scary "ololoshke_trololoshke" at the end of some queries.

### ISSUE THREAD

**Issue by ghost** [KnpLabs/knp-components#123]
Please take a look at line 30 in this file:

https://github.com/KnpLabs/knp-components/blob/master/src/Knp/Component/Pager/Event/Subscriber/Paginate/Doctrine/DBALQueryBuilderSubscriber.php#L30

"ololoshke_trololoshke" is appended to the end of the query. This was popping up in our slow query logs and looked like a potential security vulnerability in our app until we traced it down to knp-components. Quite scary!

Why is this here - debugging material accidentally left in?
Please consider removing it for the sanity of sysadmins :+1:

**Comment by danaki** [comment]
Just found "ololoshke_trololoshke" in sources, it sounds familiar
https://www.youtube.com/watch?v=sTSA_sWGM44

**Comment by salemgolemugoo** [comment]
@ChubV poke
