### ISSUE TITLE
Incorect count group by

### ISSUE THREAD

**Issue by laurentiustroia** [KnpLabs/knp-components#137]
After post [here](https://github.com/KnpLabs/KnpPaginatorBundle/issues/322#issuecomment-139546212) about count problem when do group by, they say the real problem is here with `Knp\Component\Pager\Paginator` and I want to know if this will be fixed.

**Comment by faghihian71** [comment]
hi , i have same issue what should we do

**Comment by polc** [comment]
Hello you can follow the progress of the issue here : https://github.com/KnpLabs/KnpPaginatorBundle/issues/322. It could be great if you give us the generated queries and the database version you're using so we can reproduce the problem.
