### ISSUE TITLE
PaginationInterface only defines setters

### ISSUE THREAD

**Issue by robations** [KnpLabs/knp-components#144]
For example in this sample code:

```
    $pagination = $this->paginator->paginate($query, $pageNum, 20);
    return $this->render('index.html.twig', ['pagination' => $pagination]);
```

The phpdoc return value of the paginate method has a type of `Knp\Component\Pager\Pagination\PaginationInterface`, which defines only setters. In a strict reading, we have defined a write-only black box, but the view must read from this object for it to be of use. Obviously this is PHP so we can still access things without a bunch of type errors, but this makes the API a little harder to understand.

Should there be another interface that extends `PaginationInterface` and `\Traversable`, and also defines `getCurrentPageNumber()`, `getItemNumberPerPage()`, and so on?

**Comment by polc** [comment]
Hello thanks for reporting this. You can follow the progress of the issue here: https://github.com/KnpLabs/knp-components/issues/168
