### ISSUE TITLE
The Travis CI build could not complete PHP 5.3.3 - Composer\Exception\NoSslException

### ISSUE THREAD

**Issue by mulcek** [KnpLabs/knp-components#148]
PHP 5.3.3 automated build check fails. This means all new pull requests checks fails. Please fix or allow ignore on error. Problem is in composer error:

`[Composer\Exception\NoSslException]                                          

  The openssl extension is required for SSL/TLS protection but is not availab  

  le. If you can not enable the openssl extension, you can disable this error  

  , at your own risk, by setting the 'disable-tls' option to true.`

**Comment by mulcek** [comment]
Here is  [failed job](https://travis-ci.org/KnpLabs/knp-components/jobs/154572249)

**Comment by ostrolucky** [comment]
This has been fixed via https://github.com/KnpLabs/knp-components/pull/161 ping @NiR-
