### ISSUE TITLE
Fix from knp-components broke my Paginator

### ISSUE THREAD

**Issue by marcosrachid** [KnpLabs/knp-components#153]
After the fix from knp-components, my symfony 3.1 application with knplabs/knp-paginator-bundle started to return this error from a new file called ArraySubscriber.php:

Warning: get_class() expects parameter 1 to be object, array given
500 Internal Server Error - ContextErrorException

in vendor/knplabs/knp-components/src/Knp/Component/Pager/Event/Subscriber/Sortable/ArraySubscriber.php at line 45   

`
                    $this->currentSortingFieldGetter = "get{$sortFieldName}";
                    // Getter detection
                    $class = new ReflectionClass(get_class($event->target[0]));
                    if($class->hasMethod($this->currentSortingFieldGetter)) {
                        // Sort
                        usort($event->target, array($this, "sort" . ucfirst($this->sortDirection)));
`

**Comment by rubiodamian** [comment]
Idem +1
Warning: strtolower() expects parameter 1 to be string, object given
in vendor/knplabs/knp-components/src/Knp/Component/Pager/Event/Subscriber/Sortable/ArraySubscriber.php at line 75   -
     */

`    private function sortDesc($object1, $object2)
    {
        $fieldValue1 = strtolower($object1->{$this->currentSortingFieldGetter}());
        $fieldValue2 = strtolower($object2->{$this->currentSortingFieldGetter}());
        if ($fieldValue1 == $fieldValue2) {
            return 0;`

**Comment by gcicco** [comment]
I was getting the same error along with this error: 'Uncaught PHP Exception ReflectionException: "Class  does not exist"'.

Solved by doing a composer update.

**Comment by polc** [comment]
Hello @marcosrachid @rubiodamian is this issue still relevant ?

**Comment by rubiodamian** [comment]
@polc  not for me
fixed!

**Comment by polc** [comment]
Okay I'm closing then thanks!
