### ISSUE TITLE
Paginator relies on $_GET superglobal

### ISSUE THREAD

**Issue by NiR-** [KnpLabs/knp-components#160]
The whole component relies on $_GET superglobal which is pretty bad:
* It disallows to use multiple paginations in one page ;
* Hardens ability to test code interacting with Pagiantor ;
* It's just a bad practice to rely on superglobals.

Thus, I think we should find another way to get all those parameters (maybe PSR-7?).

This issue was originally reported on [KnpLabs/knp-components#416](https://github.com/KnpLabs/KnpPaginatorBundle/issues/416).

**Comment by polc** [comment]
Issues affected (will add more when I find them) :
* https://github.com/KnpLabs/KnpPaginatorBundle/issues/416
* https://github.com/KnpLabs/KnpPaginatorBundle/issues/191

**Comment by elkangaroo** [comment]
Good to know this is already being worked on in #173 as we just stumbled upon this after the update from 1.3.4 to 1.3.5 introduced a BC break without our functional tests noticing it (BrowserKit Requests).

**Comment by polc** [comment]
@elkangaroo what BC break did you encounter in 1.3.5 ? because it's was clearly not intended!

**Comment by elkangaroo** [comment]
@polc we use the paginator with solarium and in 1.3.5 and get a `NoSuchPropertyException` exception. I created a new issue to track this at #174.

**Comment by ostrolucky** [comment]
This would probably solve oldest opened issue https://github.com/KnpLabs/knp-components/issues/90

**Comment by garak** [comment]
I guess that this issue can be closed, after merging PR mentioned above.
If closed, only 2 issues are left in [milestone](https://github.com/KnpLabs/knp-components/milestone/1): one is about raising php version (could be closed too), other is about merging component and bundle (a bit meta, IMHO it should be delayed to another milestone or rejected).

**Comment by ostrolucky** [comment]
Yep, seems it can be closed
