### ISSUE TITLE
Drop support for unmaintained PHP versions

### ISSUE THREAD

**Issue by NiR-** [KnpLabs/knp-components#162]
IMHO it's time to drop support for unmaintained PHP versions (PHP 5.3/5.4/5.5). What do you think?

**Comment by ostrolucky** [comment]
Oh yeah it was pain in the ass to make my PR work in PHP 5.3

**Comment by garak** [comment]
I'm for dropping 5.6, and maybe 7.0 too.
Go php 7.1!

**Comment by NiR-** [comment]
IMHO we should drop any PHP version :trollface: More seriously, PHP 5.6 has not ended yet and it is still under use out there. We can't simply dismiss a lot of php users just because we're lazy or anything else. I'm against supporting unmaintained php versions, but until they reach their end of life we shouldn't drop them.

**Comment by garak** [comment]
Well, you're not "dismissing" anyone. They just keep the old version.

**Comment by NiR-** [comment]
But they won't receive any bug fixes/new features from us. Or we need to maintain two branches, which is a bit painful because we would need to backport every commit from one branch to the other.

**Comment by garak** [comment]
Not receiving bug fixes/new features is a consequence on staying on a version without active support. It should be expected.

**Comment by NiR-** [comment]
> ... staying on a version without active support ...

Indeed, I concede that we could drop support for v5.6. But v7.0 is still under active support, that's exactly why I think it would be bad to drop it before the end of the year.

**Comment by garak** [comment]
I agree.
So, it all depends on the due date of the next major release: if it's before 3 December 2017, we should keep 7.0, otherwise we should go for 7.1

**Comment by NiR-** [comment]
Thank you to provide us your thoughts :+1: We'll try to define a common policy shared across our other repositories.

**Comment by garak** [comment]
It looks like this issue is solved
