### ISSUE TITLE
Move bundle into component or inverse

### ISSUE THREAD

**Issue by polc** [KnpLabs/knp-components#170]
In order to ease the maintenance we could merge the `KnpLabs/knp-components` and `KnpLabs/knp-paginator-bundle` into a single repo. 

See https://github.com/KnpLabs/knp-components/pull/167#issuecomment-329577647

**Comment by garak** [comment]
I strongly disagree.
Every bundle should be just a tiny layer between a library and Symfony, so you can easily develop an application that is not tied to Symfony itself.

**Comment by felds** [comment]
@garak that would be nice, but the lib is already strongly coupled with symfony in other ways other than the config (which makes the bundle a bundle). In this case I can't disagree with @polc;

**Comment by garak** [comment]
Strongly coupled? This library is not requiring a single Symfony component to work

**Comment by felds** [comment]
@garak Maybe not in the code sense, but the lib is most useful when working together with Doctrine. The same way a screwdriver is not coupled with screws and could be used for other things, but it really shines when driving screws! :) 

(PS: I know doctrine is not part of symfony, but I think you get what I mean.)

**Comment by garak** [comment]
Even that is not true. For example, this library is exposing three different subscribers for Doctrine pagination, and four other subscribers for non-Doctrine pagination.
I don't see why I should get a full Symfony bundle just to use pagination with Propel or with Elastica, not even mentioning the fact that I could use Doctrine without Symfony.

**Comment by ostrolucky** [comment]
I don't see how is this component coupled to Symfony either. It just uses symfony/event-dispatcher, that's all. If merged with paginatorbundle, it would then require framework-bundle.

**Comment by garak** [comment]
Since there's no agreement about this topic, and since this issue is the last one in the milestone `2.0`, I propose to move it to another milestone (so `2.0` is finally ready to be released).

**Comment by garak** [comment]
Friendly reminder: this issue is the only thing that is blocking release of version 2
Do you agree to move it to milestone 3?

**Comment by polc** [comment]
I would say let's close it for now. We can still reopen it later if we think it's still relevant.
