### ISSUE TITLE
NoSuchPropertyException with v1.3.5 (BC break?)

### ISSUE THREAD

**Issue by elkangaroo** [KnpLabs/knp-components#174]
We use the paginator with Solarium and in 1.3.5 get this exception:

`Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "score" nor one of the methods "getScore()", "score()", "isScore()", "hasScore()", "__get()", "__call()" exist and have public access in class "Solarium\Client"." at /[...]/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 509`

With "score" here being the sort field.

Backtracing to class `ArraySubscriber` line 80: `$fieldValue1 = $this->propertyAccessor->getValue($object1, $this->currentSortingField);`

I don't know if this is a BC break or if there is something else going on.

**Comment by polc** [comment]
Weird that it use the `Knp\Component\Pager\Event\Subscriber\Sortable\ArraySubscriber` instead of `Knp\Component\Pager\Event\Subscriber\Sortable\SolariumQuerySubscriber`.. can you check which subscriber was called  to sort in `1.3.4` ?

**Comment by elkangaroo** [comment]
Both in 1.3.4 and 1.3.5 it only uses ArraySubscriber.
This is the (stripped down) code calling it:

```
$this->container->get('knp_paginator')->paginate(
            array($client, $query),
            1,
            200
        );
```

**Comment by ostrolucky** [comment]
Ah yes, I see. This is because in 1.3.4 having `.` in sort field name was hard requirement, but I removed that requirement because it's not really needed in context of array. I was surprised myself when my patch has been merged as patch release, instead of minor release. 

I've pushed a fix for your issue, you might want to try it out.

**Comment by elkangaroo** [comment]
Thx @ostrolucky I tested your fix and it worked. Hope it gets merged soon.

**Comment by MisatoTremor** [comment]
While this is no bug with this project, I'm leaving that here if others run into that issue:

That exception may also occour when using an aliased field notation (i.e. ``u.name``). This might happen when you were paging an query earlier, but changed that to page the query result and forgot to change the search field ;-)

1.3.4 silently dropped that alias and just called the getter for ``name``, while the change by @ostrolucky fixed that and will try to get the property ``u`` of the target.

**Comment by polc** [comment]
The initial issue should have been solved by https://github.com/KnpLabs/knp-components/pull/192.
