### ISSUE TITLE
I want to be pull request contribute)

### ISSUE THREAD

**Issue by maranqz** [KnpLabs/knp-components#209]
Hello.

I want extend features pagination in version 2.0.
I [started ](https://github.com/maranqz/knp-components/commits/dependencies_update) update dependencies and tests because i did not notice branche "2.0". My mistake.

I want add features:
1. Direct access to pagination by `offset` 
1. `seek` pagination - using key of entity as cursor.
1. Iteration by all items. Pagination->toGenerator()
1. Add method getNext  for getting next set of items
1. Add method getPrevios for getting previous set of items

What do you think about it?
Added [interfaces](https://github.com/maranqz/knp-components/commits/offset_seek_pagination)

Thanks for answer.

**Comment by garak** [comment]
Hi @maranqz, feel free to open a PR on 2.0 branch.
Thanks
