### ISSUE TITLE
Custom pagination source provider

### ISSUE THREAD

**Issue by athlan** [KnpLabs/knp-components#211]
Since there is [pagination support](https://github.com/KnpLabs/knp-components/tree/master/src/Knp/Component/Pager/Event/Subscriber/Paginate) for:
* Arrays
* Elastica Query
* Proper
* Solarium
* Doctrine

Nowadays hexagonal architectures and Domain-Driven Design becomes more and more popular. This implicates to have some abstraction to repositories of data. It's code quality breach to expose implementation details and have pagination over it.

The proposition is to implement an interface being able to paginate over custom callback functions (one for get count, one for get items by limit/offset).

I could prepare a contribution, however wanted to make sure if Authors would like to incorporate such functionality.

Waiting for your response
Piotr.

**Comment by athlan** [comment]
Dear maintainers @polc @ostrolucky @bjoernHeneka @tristanbes @weaverryan , kind reminder.

**Comment by ostrolucky** [comment]
I'm not maintainer, just contributor. But I must say I'm not sold on this idea.

**Comment by garak** [comment]
@athlan I'm a project collaborator and interested to see your proposal.
Feel free to open a PR on 2.0 branch

**Comment by athlan** [comment]
@garak Ok, will raise one. However currently I don't see 2.0 branch (probably merged in 74a1c90cda673d4704eff77055f62af57a208a6c). Shall I branch-off from master then?

**Comment by garak** [comment]
It is: 2.0 is now master

**Comment by athlan** [comment]
PR raised: https://github.com/KnpLabs/knp-components/pull/224

**Comment by athlan** [comment]
Closing as merged.
@garak When it could be available in https://github.com/KnpLabs/KnpPaginatorBundle?

**Comment by garak** [comment]
@athlan version 2.1 should be released later this week

**Comment by athlan** [comment]
@garak will it be released together with bundle?

**Comment by garak** [comment]
Not sure. Bundle and library are following independent release processes
