### ISSUE TITLE
Using the paginator outside of a request causes a TypeError

### ISSUE THREAD

**Issue by jaikdean** [KnpLabs/knp-components#221]
If `Knp\Component\Pager\Paginator` is used outside of a request (eg. in a CLI command), it results in:

> TypeError: Argument 2 passed to Knp\Component\Pager\Event\BeforeEvent::__construct() must be an instance of Symfony\Component\HttpFoundation\Request, null given, called in vendor/knplabs/knp-components/src/Knp/Component/Pager/Paginator.php on line 120

`Knp\Component\Pager\Paginator`'s constructor takes an optional `Symfony\Component\HttpFoundation\RequestStack`, but if one isn't passed, it attempts to create a request from global vars.

**Comment by garak** [comment]
I'm wondering if old version were working (since it was using `$_GET` parameters)

**Comment by garak** [comment]
Can you try with latest version? Just require `knplabs/knp-components:^2.1@dev` and see if it works

**Comment by garak** [comment]
I just tried myself, it works.
