### ISSUE TITLE
Drop EventDispatcher component

### ISSUE THREAD

**Issue by garak** [KnpLabs/knp-components#222]
Currently, version 2 of knp-components uses some tricks to support both Symfony 3 and Symfony >=4
We should use [Symfony contract ](https://packagist.org/packages/symfony/event-dispatcher-contracts) instead.
This would require dropping support for Symfony 3.

**Comment by athlan** [comment]
Reference: https://github.com/KnpLabs/knp-components/commit/e1c3c48ddfe043756944ec598c096e7f62ce8822

**Comment by franmomu** [comment]
I don't think it's a good idea to drop support for Symfony 3 since 3.4 is a LTS version and the support finishes at Nov 2020.

**Comment by garak** [comment]
Well, we would not drop support for Symfony 3 entirely. Only version 3+ of knp-components would do, while support will be still present in knp-components 2
