### ISSUE TITLE
Sorting doesn't work with an array of exactly 2 items 

### ISSUE THREAD

**Issue by armellin** [KnpLabs/knp-components#225]
Related to [#527 of KnpLabs/KnpPaginatorBundle](https://github.com/KnpLabs/KnpPaginatorBundle/issues/527)

I have a problem when I try to sort an array made by exactly two items. I think that the bug is in Pager/Event/Subscriber/Sortable/SolariumQuerySubscriber.php.
This subscriber has this test:
```
if (is_array($event->target) && 2 == count($event->target)) {
            $event->setCustomPaginationParameter('sorted', true);
            ..............
```
So, if the target is an array made by exactly two items, the SolariumQuerySubscriber triggers the sorting, preventing the ArraySubscriber to do his job.

**Comment by garak** [comment]
What if you comment out count test? Is it working?

**Comment by armellin** [comment]
I guess that if I comment the count test out, SolariumQuerySubscriber would intercept all the arrays and ArraySubscriber would never work.
If I disable completely SolariumQuerySubscriber commenting it out in SortableSubscriber.php, then it works.

**Comment by garak** [comment]
Unfortunately, I'm not familiar with Solarium library.
We should try to understand the reason for such code.
Maybe @marekkalnik can shed some light?

**Comment by marekkalnik** [comment]
@garak no idea, I haven't worked with the library for 5 years :(

**Comment by franmomu** [comment]
@armellin can you copy & paste how you are trying to paginate?

**Comment by armellin** [comment]
@franmomu I normally use the paginator with the QueryBuilder, but in this particular case, I need to paginate the associated entities of one mother entity in her _show action_, just for sorting purposes (there is only a few of them). The (dirty?) trick I used was:

`
$paginator  = $this->get('knp_paginator');
`
`
$pagination = $paginator->paginate($entity->getRows()->toArray());
`
`
$entity->setRows($pagination);
`

Basically, I replace the collection of the associated entities with a _pagination_ of them. The twig template will know how to manage it. Technically, I am paginating an array.
Everything works, except when there are exactly two associated entities, for the reason I have explained in the first comment.
It's a minor bug, nobody needs to sort only two elements and we can survive, but when @fraserr opened the issue [#527 of KnpLabs/KnpPaginatorBundle](https://github.com/KnpLabs/KnpPaginatorBundle/issues/527) I wanted to explain why and I was suggested to open an issue here.

**Comment by garak** [comment]
@armellin are you using Solarium?

**Comment by johonunu** [comment]
@armellin @garak I am having the same problem. I am sorting array items (exactly 2 items) using paginator, but `SolariumQuerySubscriber` is triggered first, preventing `ArraySubscriber` to be called. This is the issue in `SolariumQuerySubscriber` as it only has only this check:

```php
if (is_array($event->target) && 2 == count($event->target)) {
```
In `ElasticaQuerySubscriber` it has more stricter check, so it is not called:

```php
if (is_array($event->target) && 2 === count($event->target) && reset($event->target) instanceof SearchableInterface && end($event->target) instanceof Query) {
```
