### ISSUE TITLE
Autoloader not loading bundle

### ISSUE THREAD

**Issue by Victoriam7** [KnpLabs/knp-components#226]
I am updating old code to use the latest version of Symfony; however, I suddenly get the error
```
Class "Knp\Component\Pager\Event\Subscriber\Paginate\PaginationSubscriber" used for service "knp_paginator.subscriber.paginate" cannot be found.
```
I was able to trace similar errors in other bundles to a failure of composer to load anything using psr-0. Considering that knp-components currently uses psr-0 is there a known workaround?

The project currently uses 1.2.4

**Comment by garak** [comment]
This is just a library.
You probably want to open an issue on [https://github.com/KnpLabs/KnpPaginatorBundle](KnpPaginatorBundle)
