### ISSUE TITLE
Message error thrown on pagination limit is confusing 

### ISSUE THREAD

**Issue by mboullouz** [KnpLabs/knp-components#231]
Here : [https://github.com/KnpLabs/knp-components/blob/e4edbbe12c930ed2c0cf7d624b438315471f5e83/src/Knp/Component/Pager/Paginator.php#L97](https://github.com/KnpLabs/knp-components/blob/e4edbbe12c930ed2c0cf7d624b438315471f5e83/src/Knp/Component/Pager/Paginator.php#L97) 

1. It's always a positive number (as the abs function is used) so the error message is a little bit confusing maybe should be " ...,must be a number different from 0 "
2. It's always an int as its enforced by the signature => the condition may be simplified: $limit ===0, also no need for the call to intval(..) func

**Comment by garak** [comment]
Yes.
We should instead check for a positive number (both for page and for limit).
The line that forces abs and intval should be removed.
Can you provide a PR?
