### ISSUE TITLE
Paginator Issue: problem paginating query with groupBy.

### ISSUE THREAD

**Issue by armandojs** [KnpLabs/knp-components#248]
Hello,

There's probably something I'm missing here.  I'm trying to paginate the following query using Doctrine's querybuilder:

SQL Query

```
select messages.parent_message_id, users.username, max(date_sent) as dateSent, parent_message.message_title, parent_message.read_by, items.title
from messages 
    left join users on users.id = sender_id
    left join parent_message on parent_message.id = messages.parent_message_id
    left join items on items.id =  parent_message.item_id
where messages.receiver_id = 1
group by parent_message_id, users.username;
```

Same query as Query->getSQL() output:

```
SELECT m0_.parent_message_id AS parent_message_id_0, u1_.username AS username_1, max(m0_.date_sent) AS sclr_2, p2_.message_title AS message_title_3, p2_.read_by AS read_by_4, i3_.title AS title_5 
FROM messages m0_ 
     LEFT JOIN users u1_ ON (u1_.id = m0_.sender_id)
     LEFT JOIN parent_message p2_ ON (p2_.id = m0_.parent_message_id) 
     LEFT JOIN items i3_ ON (p2_.item_id = i3_.id) WHERE m0_.receiver_id = 1
GROUP BY m0_.parent_message_id, u1_.username`
```
Error given:

> An exception occurred while executing 
> `'SELECT DISTINCT m0_.id AS id_0
> FROM messages m0_ LEFT JOIN users u1_ ON (u1_.id = m0_.sender_id) 
> LEFT JOIN parent_message p2_ ON (p2_.id = m0_.parent_message_id) 
> LEFT JOIN items i3_ ON (p2_.item_id = i3_.id) WHERE m0_.receiver_id = 1 
> GROUP BY m0_.parent_message_id, u1_.username LIMIT 5'`
> : Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'sbdb_sandbox.m0_.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

I haven't delved into the code to debug this myself however it seems that the paginator is generating this query to count the rows maybe, but it's using a column that isn't referenced in my query and that's the reason for the error.

If I set Distinct => 'false' the query runs and everything seems ok, however the 'totalCount' is incorrect.

Is there a parameter that I need to set to override the column used for counting rows?

For now I'm going to disable 'only_full_group_by' on MySQL while I keep on working.

Thanks!

**Comment by garak** [comment]
Did you also try to use `wrap-queries` option?

**Comment by armandojs** [comment]
Hi garak,

I hadn't seen that option.  I came to the conclusion that since the query uses groups the only way I could get it to work was to make the whole query a sub-query. I instead ended up manually paginating by doing a query for total rows and a second one for the data, then doing something like this:

>         $slidingPagination = new \Knp\Component\Pager\Pagination\SlidingPagination();
>         $slidingPagination->setItems($results);
>         $slidingPagination->setTotalItemCount($totalRows);
>         $slidingPagination->setCurrentPageNumber($page);

The caller was expecting a paginator interface so that's the reason for the above code.  I'll try to use `wrap-queries` a try and let you know.

Thanks!

**Comment by garak** [comment]
You can also do manually count query and add an hint for paginator.
See https://github.com/KnpLabs/KnpPaginatorBundle/blob/master/docs/manual_counting.md

**Comment by armandojs** [comment]
Hi garak,

Thanks for your help, I really appreciate it. 
I just got around to testing pagination with the `wrap queries` and `distinct` options and that did the trick.  I also did not know about manual counting.   That will definitely come in handy at some point.

Have a good one!
