### ISSUE TITLE
SolariumQuerySubscriber items iteration bug

### ISSUE THREAD

**Issue by ekosogin** [KnpLabs/knp-components#254]
Hi!
I think i've found bug in 
`\Knp\Component\Pager\Event\Subscriber\Paginate\SolariumQuerySubscriber::items`

\Solarium\QueryType\Select\Result\Result::getIterator - returned \ArrayIterator object.

That's why 
`\Knp\Component\Pager\Pagination\AbstractPagination::valid` - always returned false, because `key($this->items)` where items is \ArrayIterator returned null.

**Comment by garak** [comment]
What can we do about it?

**Comment by ekosogin** [comment]
After investigate i think the main reason is using of wrong type of "iterable" in methods
`\Knp\Component\Pager\Pagination\AbstractPagination::setItems`
`\Knp\Component\Pager\Pagination\AbstractPagination::getItems`

Iterable type can be set for generators as example and it's wrong to call count, reset, current, etc methods for this type.

I think ideal solution will be rewrite code with proper strict interfaces and make `\Knp\Component\Pager\Pagination\AbstractPagination::$items` property Iterator but this will break backward compatibility.

**Comment by garak** [comment]
Indeed, iterable Is a superset of Traversable, that is a superset of Iterator. How it can be wrong?

**Comment by ekosogin** [comment]
I just want to say that iterable type is too general. For example it can be used for generators and iterators and in this case it's wrong to call call count, reset, current, etc functions because they returned wrong result as for solarium. But it's safe for object which implements iterator and countable interface (just for example). My opinion is that iterable too general and maybe it will be better to use some known interface implementation as itarator, countable, etc for this case.

**Comment by garak** [comment]
I see.
So, can't we just change the login inside `valid` method? We could check the type of `$this->items` and call the appropriate function on it

**Comment by ekosogin** [comment]
I've made some propsal commit with prototype of the [way to fix it](https://github.com/ekosogin/knp-components/commit/e7d1c52e51019df90074769c060cae60ee99d2b6)
It's without tests just as example.
But I think it will be better to make base package with general interfaces and code and some custom separate packages with support of solarium, doctrine, etc.

**Comment by garak** [comment]
I appreciate your effort, bu this looks a bit overkilled to me. Moreover, you're changing the interface and this means BC-break.
Again, can't we simply put a check inside `valid` method?

**Comment by ekosogin** [comment]
It's just single-responsibility principle. You can do whatever you want. I just give you my vision of resolving this task. All in all i made direct call of getItems method in my app and it's also resolved issue with iteration

**Comment by ekosogin** [comment]
Also related deprecation

> Using array_key_exists() on objects is deprecated. Instead either isset() or property_exists() should be used.

 [php.net](https://www.php.net/manual/es/migration74.deprecated.php#migration74.deprecated.core.array-key-exists-objects)
`\Knp\Component\Pager\Pagination\AbstractPagination::offsetExists` - if items is object

**Comment by garak** [comment]
Question is: if we apply your solution, we'll need to release a new major version.
Instead, we need to fix current version.

**Comment by ekosogin** [comment]
> Question is: if we apply your solution, we'll need to release a new major version.
Yes, because it has incomatible changes

**Comment by garak** [comment]
So, can you provide a patch for current version?

**Comment by ekosogin** [comment]
I can but I don't see fine ways of patching of it for me so I will not provide patch. 
In my opinion it's better to use declarative interfaces then too common types and fix it in next major release.

**Comment by garak** [comment]
We could provide some conditions in `valid` and `offsetExists` methods.
Do you think it's feasible?

**Comment by ekosogin** [comment]
It's feasible but it may have some performance impact. For example 
`\Knp\Component\Pager\Pagination\AbstractPagination::count`
we should write something like 
if items is_array call count($this->items)
elseif items is Countable call $this->items->count()
elseif items is Iterator call count(iterator_to_array($this->items))
else throw some runtime exception

**Comment by garak** [comment]
I guess that performance decrease can be justified by the need of fixing a bug.
By the way, are you able to five a measure of such performance impact?

**Comment by geoff-maddock** [comment]
Our team found that we were running into this issue after the update to PHP8, and it was breaking.

We so far have ended up applying this patch using https://github.com/cweagans/composer-patches

```
--- /dev/null
+++ ../src/Knp/Component/Pager/Pagination/AbstractPagination.php
@@ -155,7 +155,10 @@
     }
 
     public function offsetExists($offset): bool
-    {
+    {   
+        if (gettype($this->items) === 'object' && get_class($this->items) == 'ArrayIterator') {
+            return array_key_exists($offset, iterator_to_array($this->items));
+        }
         return array_key_exists($offset, $this->items);
     }
```

Sharing in case this helps someone with this issue or someone with the cycles to fix this.

**Comment by garak** [comment]
@geoff-maddock thank you for providing a patch.
I'm wondering: do we need a double check for object *and* ArrayIterator? Can't we only check for the latter?
Something like `if ($this->items instanceof \ArrayIterator)`
