### ISSUE TITLE
Replace wrong terminology (e.g. "black", "white", etc.)

### ISSUE THREAD

**Issue by garak** [KnpLabs/knp-components#263]
This library currently uses options "sortFieldWhitelist" and "filterFieldWhitelist".
We should replace such terms with something like "sortFiledAcceptList" and "filterFieldAcceptList".

My proposal:
* add new options in next minor version, with same purpose
* add a deprecation in next minor version for old options
* remove old options in next major version

**Comment by flug** [comment]
Personally, I find that to want to suppress these thermal baths at all costs is ridiculous whitelist and blacklist, not any human to human relationship with regard to the colour of skins. To want to remove them at all costs is, I think, to make an amalgam of that. 
And if however you really want to reduce it to a skin color a little reminder: 

Whitelist removes everything, and lets the ones we want go through. 
Blacklist lets everything through and blocks out the ones we don't want. 

Blacklist is more optimistic than Whitelist, and I think it's better to be optimistic than pessimistic... 
But that's just my opinion.

**Comment by garak** [comment]
Thanks for your contribution.

**Comment by flug** [comment]
Thank you for potentially reading me

**Comment by garak** [comment]
Honestly, I see much more useless effort in opposing such changes than in changes themselves.
And, for what? The only reason I see here is keeping things like they are just because they _already_ are like this. Sorry, that's not enough

**Comment by flug** [comment]
Wow, that's not an opposition at all. It's just a point of view, which is made in the face of false media pressure. It's not my project, in fact you want what you want, the only thing I'm opposed to is wanting to transpose black and white to a skin color ... :)

**Comment by garak** [comment]
But you're on false assumptions too.
This issue is not mentioning "media pressure" nor anything that could be skin-related.

**Comment by flug** [comment]
if you say so...

**Comment by garak** [comment]
![GLJ1](https://user-images.githubusercontent.com/179866/87160062-a4a5e180-c2c2-11ea-8ce5-c22198b31498.gif)
