### ISSUE TITLE
must be compatible

### ISSUE THREAD

**Issue by dvdknaap** [KnpLabs/knp-components#268]
Hi,

When i want to upgrade to the latest version i get the following error:
`Declaration of ContainerITPFBLa\Paginator_f262b94::paginate($target, int $page = 1, int $limit = 10, array $options = Array): Knp\Component\Pager\Pagination\PaginationInterface must be compatible with Knp\Component\Pager\Paginator::paginate($target, int $page = 1, ?int $limit = NULL, array $options = Array): Knp\Component\Pager\Pagination\PaginationInterface`

I keep getting the same error even on symfony cache clears

Edit:
The error is fixed when you remove the var/cache/dev dir

**Comment by dvdknaap** [comment]
After removing the cache dir and to a symfony cache clear and warmup when i run my phpunit tests i get the same error again

**Comment by garak** [comment]
Are you using a custom Paginator?

**Comment by kricha** [comment]
Have same issue after update

**Comment by garak** [comment]
> Have same issue after update

And I guess you'd like  such issue to be solved. That can be possible only if you are so kind to provide some informations...

**Comment by dvdknaap** [comment]
@garak 

> Are you using a custom Paginator?
No, custom paginator

This issue is fixed when you clear the cache folder, i had to remove everything in the dev and test folder to make it work again
