### ISSUE TITLE
Argument default value inconsistence

### ISSUE THREAD

**Issue by garak** [KnpLabs/knp-components#283]
We have an inconsistence between:

```php
function paginate($target, int $page = 1, int $limit = 10, array $options = [])
```
in https://github.com/KnpLabs/knp-components/blob/master/src/Knp/Component/Pager/PaginatorInterface.php

and

```php
function paginate($target, int $page = 1, int $limit = null, array $options = [])
```
in https://github.com/KnpLabs/knp-components/blob/master/src/Knp/Component/Pager/Paginator.php

This is causing a problem in our Symfony bundle, since service is built using the interface, so it's impossible to use the "default" option. See [issue 689](https://github.com/KnpLabs/KnpPaginatorBundle/issues/689)

A possible solution is to change the interface, using `null` as default for `$limit`.
What we need to state is whether to put such change in a minor or in a major version.

**Comment by fabianoroberto** [comment]
I think it is a "minor" change because `Paginator` class is marked as final and also the unique class that implement `PaginatorInterface`. For me is not a BC if someone implement "externally" that interface.
