### ISSUE TITLE
Ability to select Doctrine's ORM Output Walkers (ex SQL Walkers) in Pager

### ISSUE THREAD

**Issue by sebablanco** [KnpLabs/knp-components#29]
Currently the Pager component offers only Doctrine's CountWalker and LimitSubqueryWalker, but there are not suitable for certain query types.

Doctrine has been using SqlWalkers (now OutputWalkers) by default in its paginator since introducing them in https://github.com/doctrine/doctrine2/commit/edd5d14b06f03187bc512c8c1c066539ee3ceed0

I have a query that uses HAVING that I pass onto the paginator, Doctrine is throwing a RuntimeExeption saying: "Cannot count query that uses a HAVING clause. Use the output walkers for pagination".
Changing the QuerySubscriber to use CountOutputWalker instead has fixed this for me.

**Comment by webdevilopers** [comment]
Looking at issue https://github.com/sonata-project/SonataAdminBundle/issues/2334 `wrap-queries` solved my HAVING clause prob:
```php
$pagination = $paginator->paginate(
    $query,
    $request->query->get('page', 1)/*page number*/,
    10/*limit per page*/,
    array('wrap-queries'=>true)
);
```

**Comment by sebablanco** [comment]
I forgot I had this issue opened, been 2 years. 

The Pager component has swapped to use Doctrine's native walkers, so this ticket is obsolete. I'll close it now.
