### ISSUE TITLE
[PHP 8.1] AbstractPagination::current() should either be compatible with Iterator::current()

### ISSUE THREAD

**Issue by pyatnitsev** [KnpLabs/knp-components#300]
Hello!

There is an deprecation warning runing on PHP 8.1:

Deprecated: Return type of Knp\Component\Pager\Pagination\AbstractPagination::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/motion/vendor/knplabs/knp-components/src/Knp/Component/Pager/Pagination/AbstractPagination.php on line 24

**Comment by garak** [comment]
Thanks for reporting.
Do you mind proposing a PR?

**Comment by pyatnitsev** [comment]
Sorry, but it's already fixed by https://github.com/KnpLabs/knp-components/blob/master/src/Knp/Component/Pager/Pagination/AbstractPagination.php. 

I faced this warning with knplabs/knp-paginator-bundle 5.4

Can you provide a release with PHP 8.1 support?

**Comment by garak** [comment]
Release v3.4.0 is out.

**Comment by pyatnitsev** [comment]
Thank you!
