### ISSUE TITLE
PaginationInterface lacks getCustomParameters method

### ISSUE THREAD

**Issue by stollr** [KnpLabs/knp-components#310]
The [`PaginationInterface`](https://github.com/KnpLabs/knp-components/blob/master/src/Knp/Component/Pager/Pagination/PaginationInterface.php) has a `setCustomParameters` method, but no `getCustomParameters` method. The `getCustomParameter` allows us to get a param, but only if you have a sepcific key. It is not possible to get all params at once.

What do you think, should we add it to the interface in the next major? With a deprecation notice if the implementing class does not have such a method.

**Comment by garak** [comment]
I can't see the benefit of adding configuration-related methods to the interface.
