### ISSUE TITLE
Introduce new exceptions

### ISSUE THREAD

**Issue by XWB** [KnpLabs/knp-components#311]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

Currently `Paginator::paginate()` throws a `LogicException` if `$limit` or ` $page` is invalid. This makes it difficult to catch the exception and shows the user a 404 page instead of a server error.

I would like to propose two new exceptions:

```php

use Knp\Component\Pager\Exception\PageLimitInvalidException;
use Knp\Component\Pager\Exception\PageNumberInvalidException;

public function paginate($target, int $page = 1, int $limit = null, array $options = []): PaginationInterface
{
        $limit = $limit ?? $this->defaultOptions[self::DEFAULT_LIMIT];
        if ($limit <= 0) {
            throw new PageLimitInvalidException(sprintf('Invalid page limit. Limit: %u: $limit must be positive non-zero integers', $limit));
        }

        if ($page <= 0) {
            throw new PageNumberInvalidException(sprintf('Invalid page number. Page: %u: $page must be positive non-zero integers', $page));
        }
}

```

**Comment by garak** [comment]
Looks good to me.
The only detail I'd change is using `%d` instead of `%u`, because we need to support negative numbers
