### ISSUE TITLE
compatibility with PHP 8.2

### ISSUE THREAD

**Issue by tdtc-hrb** [KnpLabs/knp-components#318]
SF: 6.2.0
PHP: 8.2.0
use
`composer require knplabs/knp-paginator-bundle`
something went wrong,
When I retried a second time it disappeared. . .

C:\Users\tdtc\Documents\veic-web_sf6>composer require knplabs/knp-paginator-bundle
https://repo.packagist.org could not be fully loaded (curl error 35 while downloading https://repo.packagist.org/packages.json: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to repo.packagist.org:443 ), package information was loaded from the local cache and may be out of date
Using version ^6.0 for knplabs/knp-paginator-bundle
./composer.json has been updated
Running composer update knplabs/knp-paginator-bundle
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking knplabs/knp-components (v4.0.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 131 installs, 0 updates, 0 removals
  - Downloading symfony/flex (v2.2.3)
  - Downloading symfony/runtime (v6.2.0)
  - Downloading symfony/routing (v6.2.0)
  - Downloading symfony/polyfill-mbstring (v1.27.0)
  - Downloading psr/event-dispatcher (1.0.0)
  - Downloading symfony/event-dispatcher (v6.2.0)
  - Downloading psr/log (3.0.0)
  - Downloading symfony/finder (v6.2.0)
  - Downloading symfony/filesystem (v6.2.0)
  - Downloading psr/container (2.0.2)
  - Downloading symfony/service-contracts (v3.1.1)
  - Downloading symfony/config (v6.2.0)
  - Downloading psr/cache (3.0.0)
  - Downloading symfony/cache (v6.2.0)
  - Downloading symfony/stopwatch (v6.2.0)
  - Downloading symfony/polyfill-intl-normalizer (v1.27.0)
  - Downloading symfony/polyfill-intl-grapheme (v1.27.0)
  - Downloading symfony/string (v6.2.0)
  - Downloading friendsofphp/proxy-manager-lts (v1.0.13)
  - Downloading doctrine/deprecations (v1.0.0)
  - Downloading doctrine/event-manager (1.2.0)
  - Downloading doctrine/cache (2.2.0)
  - Downloading doctrine/dbal (3.5.1)
  - Downloading doctrine/migrations (3.5.2)
  - Downloading symfony/doctrine-bridge (v6.2.0)
  - Downloading doctrine/sql-formatter (1.1.3)
  - Downloading doctrine/lexer (1.2.3)
  - Downloading doctrine/doctrine-migrations-bundle (3.2.2)
  - Downloading doctrine/instantiator (1.4.1)
  - Downloading doctrine/inflector (2.0.6)
  - Downloading doctrine/common (3.4.3)
  - Downloading doctrine/collections (1.8.0)
  - Downloading doctrine/orm (2.13.4)
  - Downloading twig/twig (v3.4.3)
  - Downloading symfony/translation (v6.2.0)
  - Downloading webmozart/assert (1.11.0)
  - Downloading phpdocumentor/reflection-common (2.2.0)
  - Downloading phpdocumentor/type-resolver (1.6.2)
  - Downloading phpdocumentor/reflection-docblock (5.3.0)
  - Downloading sebastian/version (3.0.2)
  - Downloading sebastian/type (3.2.0)
  - Downloading sebastian/resource-operations (3.0.3)
  - Downloading sebastian/recursion-context (4.0.4)
  - Downloading sebastian/object-reflector (2.0.4)
  - Downloading sebastian/object-enumerator (4.0.4)
  - Downloading sebastian/global-state (5.0.5)
  - Downloading sebastian/exporter (4.0.5)
  - Downloading sebastian/environment (5.1.4)
  - Downloading sebastian/diff (4.0.4)
  - Downloading sebastian/comparator (4.0.8)
  - Downloading sebastian/code-unit (1.0.8)
  - Downloading sebastian/cli-parser (1.0.1)
  - Downloading phpunit/php-timer (5.0.3)
  - Downloading phpunit/php-text-template (2.0.4)
  - Downloading phpunit/php-invoker (3.1.1)
  - Downloading phpunit/php-file-iterator (3.0.6)
  - Downloading theseer/tokenizer (1.2.1)
  - Downloading nikic/php-parser (v4.15.2)
  - Downloading sebastian/lines-of-code (1.0.3)
  - Downloading sebastian/complexity (2.0.2)
  - Downloading sebastian/code-unit-reverse-lookup (2.0.3)
  - Downloading phar-io/version (3.2.1)
  - Downloading phar-io/manifest (2.0.3)
  - Downloading myclabs/deep-copy (1.11.0)
  - Downloading sensio/framework-extra-bundle (v6.2.9)
  - Downloading masterminds/html5 (2.7.6)
  - Downloading symfony/dom-crawler (v6.2.0)
  - Downloading symfony/browser-kit (v6.2.0)
  - Downloading symfony/css-selector (v6.2.0)
  - Downloading symfony/messenger (v6.2.0)
  - Downloading symfony/doctrine-messenger (v6.2.0)
  - Downloading symfony/dotenv (v6.2.0)
  - Downloading symfony/expression-language (v6.2.0)
  - Downloading symfony/property-info (v6.2.0)
  - Downloading symfony/property-access (v6.2.0)
  - Downloading symfony/polyfill-intl-icu (v1.27.0)
  - Downloading symfony/options-resolver (v6.2.0)
  - Downloading symfony/form (v6.2.0)
  - Downloading symfony/http-client-contracts (v3.1.1)
  - Downloading symfony/http-client (v6.2.0)
  - Downloading symfony/intl (v6.2.0)
  - Downloading symfony/polyfill-intl-idn (v1.27.0)
  - Downloading symfony/mime (v6.2.0)
  - Downloading egulias/email-validator (3.2.1)
  - Downloading symfony/maker-bundle (v1.48.0)
  - Downloading monolog/monolog (3.2.0)
  - Downloading symfony/monolog-bridge (v6.2.0)
  - Downloading symfony/monolog-bundle (v3.8.0)
  - Downloading symfony/notifier (v6.2.0)
  - Downloading symfony/phpunit-bridge (v6.2.0)
  - Downloading symfony/process (v6.2.0)
  - Downloading symfony/proxy-manager-bridge (v6.2.0)
  - Downloading symfony/password-hasher (v6.2.0)
  - Downloading symfony/security-core (v6.2.0)
  - Downloading symfony/security-http (v6.2.0)
  - Downloading symfony/security-csrf (v6.2.0)
  - Downloading symfony/security-bundle (v6.2.0)
  - Downloading symfony/validator (v6.2.0)
  - Downloading psr/link (2.0.1)
  - Downloading symfony/web-link (v6.2.0)
  - Downloading symfony/twig-bundle (v6.2.0)
  - Downloading symfony/asset (v6.2.0)
  - Downloading symfony/webpack-encore-bundle (v1.16.0)
  - Downloading symfony/yaml (v6.2.0)
  - Downloading twig/extra-bundle (v3.4.0)
  - Installing symfony/flex (v2.2.3): Extracting archive
  - Installing symfony/runtime (v6.2.0): Extracting archive
  - Installing symfony/routing (v6.2.0): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.27.0): Extracting archive
  - Installing symfony/deprecation-contracts (v3.2.0): Extracting archive
  - Installing symfony/http-foundation (v6.2.1): Extracting archive
  - Installing psr/event-dispatcher (1.0.0): Extracting archive
  - Installing symfony/event-dispatcher-contracts (v3.2.0): Extracting archive
  - Installing symfony/event-dispatcher (v6.2.0): Extracting archive
  - Installing symfony/var-dumper (v6.2.1): Extracting archive
  - Installing psr/log (3.0.0): Extracting archive
  - Installing symfony/error-handler (v6.2.1): Extracting archive
  - Installing symfony/http-kernel (v6.2.1): Extracting archive
  - Installing symfony/finder (v6.2.0): Extracting archive
  - Installing symfony/filesystem (v6.2.0): Extracting archive
  - Installing symfony/var-exporter (v6.2.1): Extracting archive
  - Installing psr/container (2.0.2): Extracting archive
  - Installing symfony/service-contracts (v3.1.1): Extracting archive
  - Installing symfony/dependency-injection (v6.2.1): Extracting archive
  - Installing symfony/config (v6.2.0): Extracting archive
  - Installing psr/cache (3.0.0): Extracting archive
  - Installing symfony/cache-contracts (v3.2.0): Extracting archive
  - Installing symfony/cache (v6.2.0): Extracting archive
  - Installing symfony/framework-bundle (v6.2.1): Extracting archive
  - Installing symfony/stopwatch (v6.2.0): Extracting archive
  - Installing symfony/polyfill-intl-normalizer (v1.27.0): Extracting archive
  - Installing symfony/polyfill-intl-grapheme (v1.27.0): Extracting archive
  - Installing symfony/string (v6.2.0): Extracting archive
  - Installing symfony/console (v6.2.1): Extracting archive
  - Installing laminas/laminas-code (4.8.0): Extracting archive
  - Installing friendsofphp/proxy-manager-lts (v1.0.13): Extracting archive
  - Installing doctrine/deprecations (v1.0.0): Extracting archive
  - Installing doctrine/event-manager (1.2.0): Extracting archive
  - Installing doctrine/cache (2.2.0): Extracting archive
  - Installing doctrine/dbal (3.5.1): Extracting archive
  - Installing doctrine/migrations (3.5.2): Extracting archive
  - Installing doctrine/persistence (3.1.1): Extracting archive
  - Installing symfony/doctrine-bridge (v6.2.0): Extracting archive
  - Installing doctrine/sql-formatter (1.1.3): Extracting archive
  - Installing doctrine/lexer (1.2.3): Extracting archive
  - Installing doctrine/annotations (1.14.1): Extracting archive
  - Installing doctrine/doctrine-bundle (2.7.2): Extracting archive
  - Installing doctrine/doctrine-migrations-bundle (3.2.2): Extracting archive
  - Installing doctrine/instantiator (1.4.1): Extracting archive
  - Installing doctrine/inflector (2.0.6): Extracting archive
  - Installing doctrine/common (3.4.3): Extracting archive
  - Installing doctrine/collections (1.8.0): Extracting archive
  - Installing doctrine/orm (2.13.4): Extracting archive
  - Installing twig/twig (v3.4.3): Extracting archive
  - Installing symfony/translation-contracts (v3.2.0): Extracting archive
  - Installing symfony/translation (v6.2.0): Extracting archive
  - Installing knplabs/knp-components (v4.0.1): Extracting archive
  - Installing knplabs/knp-paginator-bundle (v6.0.0): Extracting archive
  - Installing webmozart/assert (1.11.0): Extracting archive
  - Installing phpdocumentor/reflection-common (2.2.0): Extracting archive
  - Installing phpdocumentor/type-resolver (1.6.2): Extracting archive
  - Installing phpdocumentor/reflection-docblock (5.3.0): Extracting archive
  - Installing phpstan/phpdoc-parser (1.15.0): Extracting archive
  - Installing sebastian/version (3.0.2): Extracting archive
  - Installing sebastian/type (3.2.0): Extracting archive
  - Installing sebastian/resource-operations (3.0.3): Extracting archive
  - Installing sebastian/recursion-context (4.0.4): Extracting archive
  - Installing sebastian/object-reflector (2.0.4): Extracting archive
  - Installing sebastian/object-enumerator (4.0.4): Extracting archive
  - Installing sebastian/global-state (5.0.5): Extracting archive
  - Installing sebastian/exporter (4.0.5): Extracting archive
  - Installing sebastian/environment (5.1.4): Extracting archive
  - Installing sebastian/diff (4.0.4): Extracting archive
  - Installing sebastian/comparator (4.0.8): Extracting archive
  - Installing sebastian/code-unit (1.0.8): Extracting archive
  - Installing sebastian/cli-parser (1.0.1): Extracting archive
  - Installing phpunit/php-timer (5.0.3): Extracting archive
  - Installing phpunit/php-text-template (2.0.4): Extracting archive
  - Installing phpunit/php-invoker (3.1.1): Extracting archive
  - Installing phpunit/php-file-iterator (3.0.6): Extracting archive
  - Installing theseer/tokenizer (1.2.1): Extracting archive
  - Installing nikic/php-parser (v4.15.2): Extracting archive
  - Installing sebastian/lines-of-code (1.0.3): Extracting archive
  - Installing sebastian/complexity (2.0.2): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (2.0.3): Extracting archive
  - Installing phpunit/php-code-coverage (9.2.20): Extracting archive
  - Installing phar-io/version (3.2.1): Extracting archive
  - Installing phar-io/manifest (2.0.3): Extracting archive
  - Installing myclabs/deep-copy (1.11.0): Extracting archive
  - Installing phpunit/phpunit (9.5.27): Extracting archive
  - Installing sensio/framework-extra-bundle (v6.2.9): Extracting archive
  - Installing masterminds/html5 (2.7.6): Extracting archive
  - Installing symfony/dom-crawler (v6.2.0): Extracting archive
  - Installing symfony/browser-kit (v6.2.0): Extracting archive
  - Installing symfony/css-selector (v6.2.0): Extracting archive
  - Installing symfony/twig-bridge (v6.2.1): Extracting archive
  - Installing symfony/debug-bundle (v6.2.1): Extracting archive
  - Installing symfony/messenger (v6.2.0): Extracting archive
  - Installing symfony/doctrine-messenger (v6.2.0): Extracting archive
  - Installing symfony/dotenv (v6.2.0): Extracting archive
  - Installing symfony/expression-language (v6.2.0): Extracting archive
  - Installing symfony/property-info (v6.2.0): Extracting archive
  - Installing symfony/property-access (v6.2.0): Extracting archive
  - Installing symfony/polyfill-intl-icu (v1.27.0): Extracting archive
  - Installing symfony/options-resolver (v6.2.0): Extracting archive
  - Installing symfony/form (v6.2.0): Extracting archive
  - Installing symfony/http-client-contracts (v3.1.1): Extracting archive
  - Installing symfony/http-client (v6.2.0): Extracting archive
  - Installing symfony/intl (v6.2.0): Extracting archive
  - Installing symfony/polyfill-intl-idn (v1.27.0): Extracting archive
  - Installing symfony/mime (v6.2.0): Extracting archive
  - Installing egulias/email-validator (3.2.1): Extracting archive
  - Installing symfony/mailer (v6.2.1): Extracting archive
  - Installing symfony/maker-bundle (v1.48.0): Extracting archive
  - Installing monolog/monolog (3.2.0): Extracting archive
  - Installing symfony/monolog-bridge (v6.2.0): Extracting archive
  - Installing symfony/monolog-bundle (v3.8.0): Extracting archive
  - Installing symfony/notifier (v6.2.0): Extracting archive
  - Installing symfony/phpunit-bridge (v6.2.0): Extracting archive
  - Installing symfony/process (v6.2.0): Extracting archive
  - Installing symfony/proxy-manager-bridge (v6.2.0): Extracting archive
  - Installing symfony/password-hasher (v6.2.0): Extracting archive
  - Installing symfony/security-core (v6.2.0): Extracting archive
  - Installing symfony/security-http (v6.2.0): Extracting archive
  - Installing symfony/security-csrf (v6.2.0): Extracting archive
  - Installing symfony/security-bundle (v6.2.0): Extracting archive
  - Installing symfony/serializer (v6.2.1): Extracting archive
  - Installing symfony/validator (v6.2.0): Extracting archive
  - Installing psr/link (2.0.1): Extracting archive
  - Installing symfony/web-link (v6.2.0): Extracting archive
  - Installing symfony/twig-bundle (v6.2.0): Extracting archive
  - Installing symfony/web-profiler-bundle (v6.2.1): Extracting archive
  - Installing symfony/asset (v6.2.0): Extracting archive
  - Installing symfony/webpack-encore-bundle (v1.16.0): Extracting archive
  - Installing symfony/yaml (v6.2.0): Extracting archive
  - Installing twig/extra-bundle (v3.4.0): Extracting archive
Package sensio/framework-extra-bundle is abandoned, you should avoid using it. Use Symfony instead.
Generating autoload files
109 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Run composer recipes at any time to see the status of your Symfony recipes.

Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package sensio/framework-extra-bundle is abandoned, you should avoid using it. Use Symfony instead.
Generating autoload files
109 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Symfony operations: 1 recipe (931990b6d050d525f0c1101d3b9e0b06)
  - Configuring knplabs/knp-paginator-bundle (>=v6.0.0): From auto-generated recipe
Executing script cache:clear [OK]
Executing script assets:install public [OK]

 What's next?

Some files have been created and/or updated to configure your new packages.
Please review, edit and commit them: these files are yours.

No security vulnerability advisories found

No security vulnerability advisories found

**Comment by garak** [comment]
I really appreciate the effort in testing the latest version of PHP.
Anyway, this is not the repository of the bundle, and moreover the bundle itself is compatible with PHP 8.2, as you can see in PR https://github.com/KnpLabs/KnpPaginatorBundle/pull/749
