### ISSUE TITLE
Exception: Attempted to call an undefined method named "setDefaultPaginatorOptions"

### ISSUE THREAD

**Issue by ssv445** [KnpLabs/knp-components#323]
Attempted to call an undefined method named "setDefaultPaginatorOptions" of class "Container8W2dAbR\PaginatorInterface_82dac15".
![iScreen Shoter - Brave Browser - 230906164105](https://github.com/KnpLabs/knp-components/assets/229291/1c5f5572-3658-4afe-a575-4223e92678c0)
![iScreen Shoter - 20230906164159350](https://github.com/KnpLabs/knp-components/assets/229291/02755455-c6fd-4211-a9c3-25bd933ba4cc)

**Configuration:**
PHP: 8.1.22  [(Using Docker 8.1.22-apache)](https://hub.docker.com/layers/library/php/8.1.22-apache/images/sha256-46543e3eeac9feb5a18187df671ff55feb248b1f591990c11a4b1550a2f6ef55?context=explore)
Symfony: 5.4.28
Xdebug & Opcache Enabled
"knplabs/knp-components": "^3.6",
"knplabs/knp-paginator-bundle": "^5.9",

If I add the definition of the `setDefaultPaginatorOptions` method in the `PaginatorInterface` (File: source/vendor/knplabs/knp-components/src/Knp/Component/Pager/PaginatorInterface.php), the issue gets **resolved**.

**Comment by garak** [comment]
So why do you attempt to call that method?
