### ISSUE TITLE
After the update, the navigation in the template disappeared.

### ISSUE THREAD

**Issue by Evgeny1973** [KnpLabs/knp-components#334]
After the update from 4.3.1 to 4.4.0, the navigation in the template disappeared.
In template
![image](https://github.com/KnpLabs/knp-components/assets/20745667/15a66e5a-2411-42da-8d6b-df65b50027fb)

Before update
![image](https://github.com/KnpLabs/knp-components/assets/20745667/ef813653-a18a-4c67-a197-34a7d75f64a1)

After update nothing's showing up
![image](https://github.com/KnpLabs/knp-components/assets/20745667/67b13b23-2cf0-4c70-aa66-c73a98df021d)

`{{ dump(pagination) }}` from template
![image](https://github.com/KnpLabs/knp-components/assets/20745667/6ab1bb16-788a-49fc-a1cd-c744ece04c65)

What can I do to get navigation back?

**Comment by garak** [comment]
Wrong repository

**Comment by Evgeny1973** [comment]
It was correct before the update and then suddenly became incorrect after?

**Comment by garak** [comment]
This is not the right repo to open the issue.

**Comment by Evgeny1973** [comment]
Ok, what is the right repository then, if the navigation disappears after an `Upgrading knplabs/knp-components (v4.3.1 => v4.4.0)`

**Comment by garak** [comment]
The bundle one

**Comment by Evgeny1973** [comment]
In [KnpPaginatorBundle](https://github.com/KnpLabs/KnpPaginatorBundle) repo?

**Comment by Evgeny1973** [comment]
Ok, thanks! But wouldn't it be weird that I'm updating one component and asking a question in the repository of another?

**Comment by garak** [comment]
Not as weird as asking a question here about something that is implemented elsewhere.
