### ISSUE TITLE
pagination not work with groupBy

### ISSUE THREAD

**Issue by exbbxak** [KnpLabs/knp-components#335]
Hi, after remove line 

> ->from('(' . $sql . ')', 'dbal_count_tbl')

 in DBALQueryBuilderSubscriber pagination not work if in queryBuilder use groupBy

**Comment by garak** [comment]
Please provide an example

**Comment by exbbxak** [comment]
`$qb = $this->connection->createQueryBuilder()
            ->select(
                'm.id',
                'TRIM(CONCAT( m.name_last, \' \', m.name_first, \' \', m.name_middle)) AS "name"',
                'm.name_last AS "lastName"',
                'm.name_first AS "firstName"',
                'm.name_middle AS "middleName"',
                'm.email',
                'm.status',
                'mg.name as groupName',
                'mr.name as roleName',
                'u.last_activity_at as lastActivityAt',
                'u.role',
            )
            ->from('lms2_members_members', 'm')
            ->leftJoin('m', 'user_users', 'u', 'm.id = u.id')
            ->leftJoin('m', 'lms2_members_members_groups', 'mmg', 'mmg.member_id = m.id')
            ->leftJoin('mmg', 'lms2_members_groups', 'mg', 'mmg.group_id = mg.id')
            ->leftJoin('m', 'lms2_members_members_roles', 'mmr', 'mmr.member_id = m.id')
            ->leftJoin('mmr', 'lms2_members_role', 'mr', 'mmr.role_id = mr.id');
        $qb->groupBy('m.id');
        if (!\in_array($sort, ['name', 'email', 'id', 'status', 'lastActivityAt', 'groupName', 'roleName'], true)) {
            throw new \UnexpectedValueException('Cannot sort by ' . $sort);
        }

        $qb->orderBy($sort, $direction === 'desc' ? 'desc' : 'asc');
        return $this->paginator->paginate($qb, $page, $size);`

**Comment by garak** [comment]
Well, I know myself what a groupBy is, merely showing a query doesn't help too much to understand the problem.

**Comment by exbbxak** [comment]
ok sorry,  problem in totalCount if in DBALQueryBuilderSubscriber on line 35 add ->from('(' . $sql . ')', 'dbal_count_tbl') from v4.3.1 all good work
![Screenshot 2024-07-26 190526](https://github.com/user-attachments/assets/c6bd3faf-3e49-4269-b5b4-d22edab0ddb6)

but if remove it line totalCount shows incorrect data
![2Screenshot 2024-07-26 190548](https://github.com/user-attachments/assets/748949ad-a3b1-4070-942c-5b586138fe9d)

and pagination not work

**Comment by Evgeny1973** [comment]
Hha, looks like my problem
![image](https://github.com/user-attachments/assets/4b8ea985-df6f-4e31-9bc7-d92cec7b0d2e)
![image](https://github.com/user-attachments/assets/755d86ac-5f9e-4cbd-8d2e-8c1ef8eb321f)

**Comment by garak** [comment]
As commented in the related PR #333, the `from` has been removed on purpose.

Someone else has had the same issue with other paginators, see this https://github.com/doctrine/dbal/issues/6371
It looks like the only way to fix this problem is injecting the DBAL Connection in the subscriber and re-building the count query from scratch.

Tagging @W0rma as the original proposer for the PR linked above

**Comment by garak** [comment]
Please check if the proposed fix works for you (I tried it myself and it works for me):

execute `composer require --no-update knplabs/knp-components "dev-fix-dbal4 as 4.4.1"`
add the following to your composer json:
```json
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/garak/knp-components.git"
    }
],
```
manually edit your `vendor/knplabs/knp-paginator-bundle/config/paginator.xml` file, adding an optional argument to the knp_paginator service. The service configuration should look like the following:

```xml
<service id="knp_paginator" class="Knp\Component\Pager\Paginator" public="true" lazy="true">
    <argument type="service" id="event_dispatcher" />
    <argument type="service" id="Knp\Component\Pager\ArgumentAccess\ArgumentAccessInterface" />
    <argument type="service" id="database_connection" on-invalid="null" /> <!-- this is the new line -->
    <tag name="proxy" interface="Knp\Component\Pager\PaginatorInterface" />
 </service>
```

run `composer update`

**Comment by Evgeny1973** [comment]
Yes!!!

**Comment by exbbxak** [comment]
You are awesome! it work! thanks!

**Comment by Evgeny1973** [comment]
@garak When will the fix be available?

**Comment by garak** [comment]
> @garak When will the fix be available?

It's not so straightforward.
The PR is merged now, so you can use our dev-master alias (instead of the fork mentioned before).
But we can't release it in a patch or minor version, because it's a BC-break. Since we need a major version, I'd like to close other issues before.

Beside that, we need a PR to add the new argument to the bundle.

**Comment by Evgeny1973** [comment]
Ok, added a line to the composer for now, waiting for release info.
"knplabs/knp-paginator-bundle": "^6.0",
**"knplabs/knp-components": "dev-master",**

**Comment by Evgeny1973** [comment]
Oh.
On dev server 
```
$qb
           ->groupBy('p.id, t.id')
            ->orderBy($sort, 'asc' === $direction ? 'asc' : 'desc') ;
       
return $this->paginator->paginate($qb, $page, $size);
```

i've got a error:
**One of listeners must count and slice given target**

On local comp all works fine.
