### ISSUE TITLE
Performance issue due to counting rows, doctrine 2.3, CountOutputWalker

### ISSUE THREAD

**Issue by vytautasgimbutas** [KnpLabs/knp-components#65]
I'm not really sure whether this is a doctrine issue or knp, but this could be fixed by not using Doctrine\ORM\Tools\Pagination\CountOutputWalker.

When Doctrine CountOutputWalker is used the generated SQL looks like this:
SELECT COUNT(*) AS dctrn_count FROM (SELECT DISTINCT id6 FROM (SELECT q0_.subject AS subject0, q0_.views AS views1, q0_.content AS content2, q0_.active AS active3, q0_.created_at AS created_at4, q0_.updated_at AS updated_at5, q0_.id AS id6, q0_.user_id AS user_id7, q0_.category_id AS category_id8 FROM question q0_ ORDER BY q0_.id DESC) dctrn_result) dctrn_table

mysql> SELECT COUNT(*) AS dctrn_count FROM (SELECT DISTINCT id6 FROM (SELECT q0_.subject AS subject0, q0_.views AS views1, q0_.content AS content2, q0_.active AS active3, q0_.created_at AS created_at4, q0_.updated_at AS updated_at5, q0_.id AS id6, q0_.user_id AS user_id7, q0_.category_id AS category_id8 FROM question q0_ ORDER BY q0_.id DESC) dctrn_result) dctrn_table;
+-------------+
| dctrn_count |
+-------------+
|       59328 |
+-------------+
1 row in set (0.24 sec)

and when it's not used:
mysql> SELECT count(DISTINCT q0_.id) AS sclr0 FROM question q0_;
+-------+
| sclr0 |
+-------+
| 59328 |
+-------+
1 row in set (0.02 sec)

**Comment by polc** [comment]
This has been fixed since.
