### ISSUE TITLE
Use doctrine builtin pagination

### ISSUE THREAD

**Issue by kl3ryk** [KnpLabs/knp-components#69]
Here https://github.com/KnpLabs/knp-components/commit/d4ecf57dd447c18d7b267693e1ce2b01ed6d2ee0 are some fixes with counting items. I wrote about problems with counting here: https://github.com/KnpLabs/KnpPaginatorBundle/issues/187. I've done some research and found that there is a perfect soultion: http://docs.doctrine-project.org/en/latest/tutorials/pagination.html.

I think it fits our needs (like a raper ;)).

I see you use some code from them (eg,: https://github.com/KnpLabs/knp-components/blob/master/src/Knp/Component/Pager/Event/Subscriber/Paginate/Doctrine/ORM/Query/Helper.php) but maybe it will be ok to just extend Doctrine Pagination and use if version is equal or above 2.2.0.

What do you think?

**Comment by polc** [comment]
It has been done in https://github.com/KnpLabs/knp-components/pull/115.
